### ISSUE TITLE
Vesting fvm until 2024.7.03

### ISSUE THREAD

**Issue by oxSaturn** [Velocimeter/frontend#223]
User ran into `voting lock can be 52 weeks max` error.

I.e., could be caused by this line of code https://github.com/Velocimeter/frontend/blob/d34b2bd4ad5ac117374634ce4527ef942760b716/Frontend-v1-Original/components/ssVest/lockDuration.tsx#L27

**Comment by t0rbik** [comment]
does it need chores to pulse and canto?

**Comment by oxSaturn** [comment]
> does it need chores to pulse and canto?

yep, will cherry pick it.

**Comment by oxSaturn** [comment]
Fixed.
