### ISSUE TITLE
Wrong Reward Estimate for voted nft

### ISSUE THREAD

**Issue by oxSaturn** [Velocimeter/frontend#75]
Say I have a voted nft, now if I drag the slider to estimate reward of voting other pairs, the `Reward Estimate` could return wrong value:

![](https://user-images.githubusercontent.com/126733611/235842716-96f26496-a715-470a-a973-52336e9300a3.png)

As you can see from the screenshot, the total bribes value is only `$0.04` while `Reard Estimate` returns `$979.24`.

**Comment by t0rbik** [comment]
Merged #81. Also it explicitly says estimate.
According to [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/estimate) estimate is:

> a **guess** of what the size, value, amount, cost, etc. of something might be.

> a **judgment** or calculation of **approximately** how large or how great something is.

**Comment by t0rbik** [comment]
Although in regard to the attached screenshot it is fair to say that the situation is more of a rough estimate.
